### PR TITLE
Update graylog.js

### PR DESCRIPTION
**Pull request by meiremans**
Version Bump for messages

### CODE REVIEW

**Comment by ronkorving** [comment]
Can you provide some context for this change?

**Comment by meiremans** [comment]
Yes, my version of Graylog does not work with 1.0 : Graylog 2.2.3+7adc951 on graylog.lxd (Oracle Corporation 1.8.0_131 on Linux 4.4.0-38-generic)

**Comment by ronkorving** [comment]
@stelcheck To your knowledge, could this cause any issues on other services that use Gelf?

**Comment by stelcheck** [comment]
I don't believe so.

**Comment by ronkorving** [comment]
Then I think we should merge this PR. In the end, Graylog 2 *is* the main server application for this module. If it were to be problematic for any other services, I would've suggested making it configurable. Maybe some day we still may opt to do so. But for now, maybe merge and release this? What do you think?

**Comment by stelcheck** [comment]
Sounds good. Indeed, if this poses problem the fix would be trivial enough.

**Comment by ronkorving** [comment]
Thank you for the contribution, @meiremans !

**Comment by ronkorving** [comment]
Released as v0.2.0 on https://www.npmjs.com/package/graylog2

**Pull request merged**
